#!/usr/bin/env python
"""Generate Chinese translation of JRN209 Reflection Guide."""

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import datetime

doc = Document()

for section in doc.sections:
    section.top_margin = Cm(2.54)
    section.bottom_margin = Cm(2.54)
    section.left_margin = Cm(2.54)
    section.right_margin = Cm(2.54)

style = doc.styles['Normal']
font = style.font
font.name = 'Times New Roman'
font.size = Pt(12)
style.paragraph_format.line_spacing = 2.0
style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

BBC_RED = RGBColor(0xB8, 0x00, 0x00)
BBC_DARK = RGBColor(0x1A, 0x1A, 0x1A)
BBC_GREY = RGBColor(0x54, 0x56, 0x58)
BBC_LIGHT = RGBColor(0x8A, 0x8C, 0x8E)

for i in [1, 2, 3]:
    h_style = doc.styles[f'Heading {i}']
    h_font = h_style.font
    h_font.name = 'Times New Roman'
    h_font.color.rgb = BBC_RED
    if i == 1: h_font.size = Pt(16)
    elif i == 2: h_font.size = Pt(13)
    else: h_font.size = Pt(12)
    h_font.bold = True

def heading(text, level=1):
    return doc.add_heading(text, level=level)

def body(text):
    p = doc.add_paragraph(text)
    return p

def bullet(text):
    p = doc.add_paragraph(text, style='List Bullet')
    p.paragraph_format.line_spacing = 2.0
    return p

def quote_block(text):
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Cm(1.27)
    p.paragraph_format.right_indent = Cm(1.27)
    p.paragraph_format.space_before = Pt(4)
    p.paragraph_format.space_after = Pt(4)
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(11)
    run.font.color.rgb = BBC_GREY
    return p

def example(title, what_happened, why_matters, where_to_use, sample_text=None):
    heading(title, 3)
    p1 = doc.add_paragraph()
    r1 = p1.add_run('发生了什么：')
    r1.bold = True; r1.font.color.rgb = BBC_RED
    p1.add_run(what_happened)
    p2 = doc.add_paragraph()
    r2 = p2.add_run('为什么值得写进反思：')
    r2.bold = True; r2.font.color.rgb = BBC_RED
    p2.add_run(why_matters)
    if sample_text:
        quote_block(sample_text)
    p3 = doc.add_paragraph()
    r3 = p3.add_run('放入位置：')
    r3.bold = True; r3.font.color.rgb = BBC_GREY
    p3.add_run(where_to_use)
    doc.add_paragraph()

# ===== TITLE PAGE =====
for _ in range(8):
    doc.add_paragraph()

p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run('JRN209 期末项目'); r.font.size = Pt(28); r.font.color.rgb = BBC_RED; r.font.name = 'Times New Roman'; r.bold = True

p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run('反思写作指南（中文版）'); r.font.size = Pt(18); r.font.color.rgb = BBC_DARK; r.font.name = 'Times New Roman'

p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run('来自设计与开发过程的16个真实案例'); r.font.size = Pt(13); r.font.color.rgb = BBC_GREY

doc.add_paragraph()
p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run(f'生成日期：{datetime.date.today().strftime("%Y年%m月%d日")}  |  News Online 门户  |  厦马 JRN209'); r.font.size = Pt(10); r.font.color.rgb = BBC_LIGHT

doc.add_page_break()

# ===== HOW TO USE =====
heading('使用说明', 1)
body('本文档包含16个具体案例，全部来自News Online新闻门户项目的真实设计会话、git提交记录和代码库。每个案例对应JRN209课程作业（期末项目，占40%）所要求的2页反思报告中的特定部分。')
body('使用方法：')
bullet('通读全部16个案例，了解项目过程中实际发生了什么。')
bullet('选择8-10个与你自身体验最吻合的案例。')
bullet('用自己的话重写每个案例——转述所有内容。这是保持Turnitin AI相似度低于10%的关键。')
bullet('将重写后的每个案例放入反思报告的对应部分（第2-5节）。')
bullet('加入你自己的真实想法和感受。案例提供事实依据，你提供个人反思。')
body('重要提醒：课程作业明确要求"without any materials generated by AI tools"并且SIMILARITY/AI INDEX必须低于10%。请将本文档仅作为参考资料使用，不要复制粘贴。')

# ===== REQUIREMENTS =====
heading('课程作业要求', 1)
body('JRN209课程作业明确要求反思以下内容：')
bullet('设计和开发在线新闻平台的经验')
bullet('设计和开发过程中遇到的挑战')
bullet('为克服挑战所采用的策略')
bullet('整个过程中学到的经验教训')
bullet('网站在吸引受众方面的有效性')
bullet('网站在传递新闻内容方面的有效性')
bullet('网站在维护新闻原则方面的有效性')
bullet('改进方向和未来发展')
body('格式要求：Times New Roman 12pt，双倍行距（2.0行距），1英寸（2.54cm）四周页边距，底部居中页码，两端对齐。精确2页。')

heading('建议的5部分结构', 2)
bullet('第1节：引言——项目概述和范围（1段）')
bullet('第2节：设计过程与策略——设计理念、迭代方法、移动优先策略（2-3段）')
bullet('第3节：挑战与解决方案——3-4个具体技术/设计挑战及解决过程（2段）')
bullet('第4节：效果评估——网站如何吸引受众、传递新闻内容、维护新闻原则（2段）')
bullet('第5节：改进方向与未来发展——对当前局限的诚实评估及具体后续步骤（1-2段）')

heading('需要融入的新闻学概念', 2)
body('将这些概念自然地编织进反思中，不要生硬罗列：')
bullet('倒金字塔结构——在讨论故事卡片层级和页面布局时提及')
bullet('新闻价值（时效性、接近性、影响力）——在谈到实时数据模块（天气、股市、世界杯比分）时引用')
bullet('署名 attribution——在解释为什么每篇故事卡片都带有记者署名时讨论')
bullet('受众参与——关联到投票趋势图、评论区、实时比分等模块')
bullet('移动优先响应式设计——作为核心设计策略而非事后补充来讨论')
bullet('多媒体叙事——提及视频嵌入、音频播放器、数据可视化')
bullet('伦理标准——引用广告标注、署名准确性、新闻与观点的分离')

doc.add_page_break()

# ===== SECTION 2 =====
heading('第2节案例：设计过程与策略', 1)
body('在反思的第2节中使用这些案例，证明你的设计决策是经过深思熟虑和调研的，而非随意选择。')

example(
    '案例A：选择BBC作为设计参考',
    '第一版原型是中文界面、通用占位样式。经过初步评审后，决定切换为英文并采用BBC News作为主要视觉参考。BBC News是全球最受认可的英语新闻品牌，其设计模式（红色报头、衬线标题、密集编辑网格、"最多阅读"侧边栏）经过数十年用户测试和迭代。',
    '这表明你不是复制模板，而是在研究行业标杆后做出的设计参考选择。你可以讨论BBC的信息层级如何教会你：首页故事的排列本身就是一种编辑行为——每个故事卡片的大小和位置都在向读者传递重要性的判断。',
    '第2节，A段（设计理念）',
    '我选择BBC News作为主要设计参考，因为它的视觉语言代表了数字新闻呈现的黄金标准。研究BBC的布局让我明白，首页上故事层级本身就是一种编辑行为：每个故事卡片的大小和位置，传达了出版物对该故事重要性的判断。'
)

example(
    '案例B：自托管字体而非使用Google CDN',
    '最初使用Google Fonts CDN链接。后来替换为存储在本地fonts/目录的自托管.woff2字体文件，通过@font-face声明加载。这个决定消除了一个阻塞渲染的外部网络请求，使网站在首次加载后无需互联网即可运行，并避免了Google服务在某些地区被屏蔽或限速的问题。',
    '这是一个具体的、可验证的技术决策，有明确的理由：可访问性、性能、离线能力。大多数学生项目从不考虑字体托管策略，这体现了超出作业最低要求的思考。',
    '第2节（设计理念）或第3节（作为挑战解决）'
)

example(
    '案例C：天气模块——三个版本，一个设计系统',
    '天气组件经历了三个不同的设计迭代，每个版本都有独立的git提交记录。版本1使用Apple风格的玻璃拟态和粒子画布动画。版本2移除了画布动画并将颜色token对齐到网站BBC红色调色板。版本3将整个模块重新配色以匹配侧边栏其他部分使用的中性灰色卡片美学。',
    '这是项目中最清晰的迭代优化案例。第一版技术上令人印象深刻但视觉上不协调。认识到这一点并退回到服务于整体系统的设计，而非炫技，体现了设计成熟度：知道何时做减法比知道何时做加法更难。',
    '第2节，B段（迭代方法）',
    '我最初构建了一个带有粒子动画的玻璃拟态天气模块，灵感来自Apple的天气应用。单独看很出色，但把它放在"最多阅读"列表和"有话要说"投票旁边后，半透明玻璃效果与网站平面的编辑美学产生了冲突。我移除了动画，将卡片重新配色为使用与侧边栏其他部分相同的中性设计token。结果是信息呈现而不分散注意力——这正是新闻侧边栏应该做到的。'
)

example(
    '案例D：故事图片宽高比——三次尝试才做对',
    '故事卡片的图片宽高比需要三次迭代才能在所有上下文中正确工作。第一次使用16:9，导致卡片下方留白过多。第二次改为3:2，解决了卡片间距问题但又在分类特色图片下方引入了新的留白问题。最终方案结合了16:9和max-height: 380px，在保持标准比例的同时约束了高度。',
    '这是那种平凡但真实的设计问题，能够区分用心之作和模板填充。单个CSS属性（aspect-ratio）在不同上下文（故事网格 vs. 分类特色区域）中表现不同，解决方案需要组合两个约束条件而非找到某个魔法数值。',
    '第2节，B段（迭代方法）或第3节（挑战）'
)

example(
    '案例E：增加第10篇故事以平衡视觉构成',
    '故事网格原本有9张卡片。侧边栏（最多阅读+天气+世界杯比分+投票+视听）延伸到9卡片网格下方，在布局中留下尴尬的空白区域。增加第10篇故事卡片是专门为了在视觉上平衡两列。',
    '这表明你在将页面作为整体构成来思考，而不仅仅是填充模板。增加内容的决定是出于列与列之间的视觉平衡，而非机械的"加更多新闻"。',
    '第2节，B段或第3节'
)

example(
    '案例F：移动优先设计搭配截图验证',
    '项目包含16张截图，在三个断点捕捉：390px手机端、1440px平板端、1920px桌面端。文件命名讲述了自己的故事：page-1920-fixed.png、page-1920-debug.png、page-1920-final.png、page-all-fixed.png。每张截图代表一个QA检查点，在继续之前对布局进行了视觉验证。',
    '你不是只写媒体查询然后祈祷能行。你在每个断点都捕捉了实际渲染并进行了比较。这是真实的QA工作流，不是学生走捷径。',
    '第2节，C段（移动优先策略）'
)

doc.add_page_break()

# ===== SECTION 3 =====
heading('第3节案例：挑战与解决方案', 1)
body('在反思第3节中使用这些案例。最有说服力的挑战是具体和技术性的——避免模糊的表达如"CSS很难"。要写出具体的CSS属性、具体的浏览器、具体的解决方案。')

example(
    '案例G：侧边栏布局对齐——一次多提交的调试过程',
    '侧边栏和下方的分类网格不断偏移错位。CSS使用了grid-template-columns: 1fr 320px，但当内容列具有不同的自然高度时，浏览器的自动布局算法产生了意外的间隙。修复需要CSS Grid调整和删除一个破坏DOM结构的多余</div>闭合标签。',
    '这是CSS Grid引入的教科书级布局问题：混合固定列和弹性列。你可以解释修复不是单个属性更改，而是grid调整和DOM清理的组合——这正是真实调试的工作方式。',
    '第3节（挑战与解决方案）'
)

example(
    '案例H：跨浏览器:user-invalid兼容性',
    '评论表单验证使用了CSS :user-invalid来仅在用户与字段交互后才显示错误样式。然而，浏览器对该伪类的支持各不相同。Chrome 119+、Firefox 88+和Safari 16.5+支持它，但更旧的版本需要回退模式。修复方案同时使用了:user-invalid和一个JavaScript应用的fallback class。',
    '这展示了对渐进增强和跨浏览器兼容性的意识——这些是生产环境中重要但课程项目中常被忽视的概念。',
    '第3节（挑战与解决方案）'
)

example(
    '案例I：BBC标准色彩系统——不只是一个色值',
    'BBC红是#B80000。但单个色值不足以构成完整的设计系统。hover状态需要#8B0000，微妙的背景色调需要rgba(184,0,0,0.08)，而focus、active、disabled状态各自需要不同的色度。让每个交互状态都感觉像是同一色系，需要测试页面上的每个按钮、链接和表单元素。',
    '这展示了对色彩系统的理解而非单一色值选取。初学者选一个红色到处用。你构建了一个三token红色系统（--c-red、--c-red-dark、--c-red-light），处理每种交互状态的同时保持视觉一致性。',
    '第3节（挑战与解决方案）',
    'BBC红是一个具体的色值，但用它做设计意味着构建一个色彩系统，而非选取一个颜色。主CTA使用#B80000，hover状态暗化为#8B0000而不失去暖度，微妙的背景高亮使用8%透明度变体。让每个交互状态都感觉是同一色系，需要测试页面上的每一个按钮、链接和表单元素。'
)

example(
    '案例J：实时数据集成与优雅降级',
    '三个模块依赖外部实时数据：天气卡片获取吉隆坡的OpenWeatherMap数据，股市ticker显示10个市场指数及涨跌指示，世界杯2026比分模块连接ESPN实时API每60秒自动刷新。每个都可能因API速率限制、网络问题或过期密钥而失败。每个模块都有加载状态，并且在失败时优雅降级到上次已知状态而非破坏整个页面。',
    '这展示了真正的软件工程思维：问"当这个失败时会发生什么？"优雅降级的概念意味着即使外部数据源不可用，页面也必须继续运行。外部数据是加分项，不是基础。',
    '第3节（挑战与解决方案）',
    '世界杯比分模块每60秒从实时API刷新。但网络请求会失败。如果API返回错误，模块显示上次已知状态而非损坏的组件或空白区域。天气卡片和股市ticker也是同样的原则：每个模块自包含，一个模块的失败不影响页面其他部分。'
)

doc.add_page_break()

# ===== SECTION 4 =====
heading('第4节案例：效果评估', 1)
body('在反思第4节中使用这些案例，证明你按照课程作业明确要求的三个标准评估了你的网站：吸引受众、传递新闻内容、维护新闻原则。')

example(
    '案例K：将评论区从首页移到文章页',
    '第一版原型将评论区直接放在首页。研究BBC架构后，评论区被移到每篇独立文章页面的底部，读者只有在点击进入完整故事后才能访问。',
    '这是一个植根于理解新闻受众行为的UX决策。首页的评论区制造噪音、稀释编辑声音。文章页的评论区则围绕该特定故事创造聚焦讨论。将两者分开，维护了编辑内容与读者意见之间的界限——这是核心新闻原则。',
    '第4节——既是"吸引受众"也是"维护新闻原则"',
    '将评论区放在文章页而非首页是一个深思熟虑的编辑决定。首页呈现经编辑筛选的内容。文章页则为公共讨论打开空间。将这两个功能分开，维护了出版物观点与读者观点之间的清晰界限。'
)

example(
    '案例L：带趋势可视化的投票——超越最低要求',
    '"有话要说"投票不只是简单计票器。投票后，用户看到：百分比分解的柱状图、显示"本周观点如何变化"的趋势线（将当前结果与模拟的上周对比）、绿色确认对勾标记、带有实时脉冲动画点的总投票数显示。',
    '这将一个基础投票变成了社区观点追踪器。趋势图给读者一个回来看观点如何演变的理由。这直接回应了课程作业要求的"通过鼓励用户参与、反馈和讨论来培养社区感"。',
    '第4节——"吸引受众"'
)

example(
    '案例M：遵循UX研究的评论表单验证',
    '评论表单使用CSS :user-invalid而非:invalid来控制验证样式。这意味着尚未触碰评论框的用户看不到红色边框——错误只在用户与字段交互并留空后才出现。这遵循了Baymard Institute的结账UX研究，该研究发现过早验证是表单UX中最常见的失败。',
    '你不只是实现了验证——你对何时显示验证做出了有研究依据的决策。将设计决策与学术UX研究关联，正是大学课程看重的那种思维方式。',
    '第4节——"传递新闻内容"或"吸引受众"'
)

example(
    '案例N：广告标注与用户控制',
    '横幅广告包含清晰可见的"ADVERTISEMENT"标签和一个带有无障碍aria-label的关闭按钮。广告使用明显的灰色背景，通过边框和间距与编辑内容视觉分离。',
    '这直接展示了新闻伦理：广告绝不能与编辑内容混淆。清晰的标注维护了读者信任——这是课程作业明确要求的核心原则。关闭按钮尊重读者拒绝广告的选择，这超出了最低伦理要求。',
    '第4节——"维护新闻原则"'
)

example(
    '案例O：每篇故事都有署名',
    '每一张故事卡片、每一个分类特色、每一条"最多阅读"项目都带有署名。例如："By Sarah Chen"、"By James Mitchell"、"By Dr. Elena Rossi"、头条故事上的"By Lin Xiang"。没有内容是匿名的。',
    '署名 attribution 是课程作业明确列出的新闻伦理之一："Accuracy, Fairness, Objectivity and Proper attribution。"署名创造问责——读者确切知道谁写了什么，记者的职业声誉与其作品挂钩。',
    '第4节——"维护新闻原则"',
    '门户上每篇新闻故事都带有署名，包括头条故事上我自己的名字。署名不是装饰——它是一种伦理承诺。当读者看到"By Lin Xiang"，他们知道一个真实的人站在这些文字背后，可以为其准确性负责。'
)

doc.add_page_break()

# ===== SECTION 5 =====
heading('第5节案例：改进方向', 1)
body('诚实地承认局限比假装一切完美更有说服力。下面的每个局限都有明确的原因和清晰的解决路径——这向评分人展示了你能够批判性地评估自己的工作。')

example(
    '案例P：已知局限与未来发展路径',
    '承认五项局限：（1）头条故事内容和视频仍是占位符，等待课程作业第一部分的现场报道视频完成；（2）部分二级文章链接指向#锚点而非完整页面，因为构建全部42篇文章页面超出了单学期项目范围；（3）评论存储在浏览器内存中，刷新页面后消失，因为本项目聚焦前端设计和客户端交互；（4）搜索面板仅有UI，没有实际的搜索索引；（5）网站没有内容管理系统，所有内容更改需要直接编辑HTML。',
    '有明确原因的诚实局限比模糊的"需要改进"更有说服力。每个局限都有具体原因（等待课程其他部分、项目范围、前端聚焦）和具体的前进路径。这向评分人展示了你能够批判性地评估自己的工作。',
    '第5节',
    '网站当前的局限主要是范围和顺序的函数。头条故事等待构成本课程作业第一部分的现场报道视频；书面故事必须基于那份原始报道。评论在浏览器中工作但不持久化到服务器，因为本项目聚焦前端设计和客户端交互。这些是选择，不是疏忽，每个都有在未来迭代中解决的清晰路径。'
)

heading('格式检查清单', 2)
bullet('全文 Times New Roman，12pt')
bullet('双倍行距（2.0行距）')
bullet('1英寸（2.54cm）四周页边距')
bullet('页码，底部居中')
bullet('两端对齐')
bullet('精确2页——不是1.5页，也不是2.5页')
bullet('保存为.docx（WORD格式）')
bullet('文件名：组长姓名_组长学号')
bullet('包含可编辑WORD格式的评分标准（不要粘贴为图片）')
bullet('附上Turnitin截图，显示相似度/AI指数低于10%')

heading('示例开头段落', 2)
body('请完全用自己的话重写。以下仅用于展示语气、长度和细节水平。')
quote_block(
    '本反思审视了为JRN209期末项目设计和开发在线新闻门户的过程。该网站从零开始使用HTML、CSS和JavaScript构建，'
    '采用BBC风格的编辑设计，自托管字体，零外部依赖。经过八天、二十余次设计修订的迭代开发，项目从基础六故事首页演变为'
    '一个功能完备的新闻平台，拥有八个分类板块的42篇故事，实时天气、金融市场和体育比分数据模块，以及包括带趋势可视化的'
    '投票和文章级评论区在内的多个受众参与功能。本文讨论了塑造最终产品的设计策略、技术挑战和编辑决策，并评估了其在'
    '传递新闻内容、吸引读者和维护新闻标准方面的有效性。'
)

# ===== SAVE =====
output_path = 'D:/Projects/personal/jrn209-news-portal/JRN209-Reflection-Guide-ZH.docx'
doc.save(output_path)
print(f'Chinese document saved to: {output_path}')
print('Done.')
